[mpdscribble]
host = 127.0.0.1
port = 6600
log = /home/robert3005/.mpdscribble/mpdscribble.log
verbose = 2
sleep = 1
musicdir = ~/Music

[last.fm]
url = http://post.audioscrobbler.com/
username = dzobert
journal = /home/robert3005/.mpdscribble/lastfm.journal

